trojuhelniky:
	clang TrojuhelnikLH.c -o TrojuhelnikLH
	clang TrojuhelnikPH.c -o TrojuhelnikPH
	clang TrojuhelnikLD.c -o TrojuhelnikLD
	clang TrojuhelnikPD.c -o TrojuhelnikPD
	clang TrojuhelnikH.c -o TrojuhelnikH
	clang TrojuhelnikD.c -o TrojuhelnikD
	clang TrojuhelnikP.c -o TrojuhelnikP
	clang TrojuhelnikL.c -o TrojuhelnikL

diamant:
	clang Diamant.c -o Diamant